name: visprog
dependencies:
  - python=3.10
  - pip
  - jupyter
  - ipykernel
  - Pillow
  - scipy
  - openai
  - ipdb
  - transformers
  - pytest
  - opencv-python
  - face-detection
  - augly
  - diffusers
  - accelerate
